# Generated by Django 4.0.3 on 2022-04-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='nacimiento',
        ),
    ]
