# Generated by Django 4.0.3 on 2022-04-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_familiar_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Familiar2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Familiar3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
