# Generated by Django 4.0.3 on 2022-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_familiar1_familiar2_familiar3_delete_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
